/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadIdRouteImport } from './routes/$threadId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebSearchRouteImport } from './routes/api/web-search'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiCrProxyRouteImport } from './routes/api/cr-proxy'

const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebSearchRoute = ApiWebSearchRouteImport.update({
  id: '/api/web-search',
  path: '/api/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrProxyRoute = ApiCrProxyRouteImport.update({
  id: '/api/cr-proxy',
  path: '/api/cr-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/api/cr-proxy': typeof ApiCrProxyRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/api/cr-proxy': typeof ApiCrProxyRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/api/cr-proxy': typeof ApiCrProxyRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/api/cr-proxy'
    | '/api/transcribe'
    | '/api/web-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$threadId'
    | '/api/cr-proxy'
    | '/api/transcribe'
    | '/api/web-search'
  id:
    | '__root__'
    | '/'
    | '/$threadId'
    | '/api/cr-proxy'
    | '/api/transcribe'
    | '/api/web-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadIdRoute: typeof ThreadIdRoute
  ApiCrProxyRoute: typeof ApiCrProxyRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiWebSearchRoute: typeof ApiWebSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$threadId': {
      id: '/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-search': {
      id: '/api/web-search'
      path: '/api/web-search'
      fullPath: '/api/web-search'
      preLoaderRoute: typeof ApiWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cr-proxy': {
      id: '/api/cr-proxy'
      path: '/api/cr-proxy'
      fullPath: '/api/cr-proxy'
      preLoaderRoute: typeof ApiCrProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadIdRoute: ThreadIdRoute,
  ApiCrProxyRoute: ApiCrProxyRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiWebSearchRoute: ApiWebSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
